version: 2.1

orbs:
  kube: circleci/kubernetes@0.11.0

commands:
  setup_ruby:
    steps:
      - checkout
      - run: |
          gem install bundler
      - run: |
          bundle update --bundler

jobs:
  test-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: mongo:4.1.4-xenial
    steps:
      - run: |
          mkdir /tmp/test-results
      - run: |
          mkdir -p /tmp/test-results/rspec
      - setup_ruby
      - run: |
          bundle exec rspec \
          --format RspecJunitFormatter --out /tmp/test-results/rspec/results.xml \
          --format html --out /tmp/html-results/results.html \
          --format progress spec/
      - store_test_results:
          path: /tmp/test-results/rspec
      - store_artifacts:
          path: /tmp/html-results
          destination: results
  doc-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - run: |
          mkdir /tmp/campaigns
      - setup_ruby
      - run: |
          bundle exec yard doc -o /tmp/campaigns controllers/ decorators/ services/
      - store_test_results:
          path: /tmp/campaigns
      - store_artifacts:
          path: /tmp/campaigns
          destination: campaigns
  rubocop-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - run: |
          mkdir /tmp/campaigns
      - setup_ruby
      - run: |
          bundle exec rubocop -F -f h -o /tmp/campaigns/results.html controllers/ decorators/ services/
      - store_test_results:
          path: /tmp/campaigns
      - store_artifacts:
          path: /tmp/campaigns
          destination: campaigns
  build-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
      - run: |
          gem install virtuatable
      - run: |
          virtuatable docker create campaigns
  deploy-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - kube/install-kubectl
      - checkout
      - run: |
          mkdir $HOME/.kube
      - run: |
          echo -n "${KUBERNETES_CONFIG}" | base64 --decode > $HOME/.kube/config
      - run: |
          gem install virtuatable
      - run: |
          virtuatable kube create campaigns --retry=3
  tag-job:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "58:25:6e:69:96:a3:5a:e2:2f:2f:92:1b:eb:64:04:be"
      - checkout
      - run: |
          gem install virtuatable
      - run: |
          virtuatable docker latest campaigns | xargs git tag
      - run: |
          git push --tags
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - rubocop-job
      - test-job:
          requires:
            - rubocop-job
      - doc-job:
          requires:
            - rubocop-job
      - build-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
      - tag-job:
          requires:
            - build-job
          filters:
            branches:
              only: master